name: Release
on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full Git history is available

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Read version from package.json
        id: get_version
        run: echo "PACKAGE_VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${PACKAGE_VERSION}" >/dev/null 2>&1; then
            echo "Tag v${PACKAGE_VERSION} already exists."
            echo "EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag v${PACKAGE_VERSION} does not exist."
            echo "EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Create Git tag
        if: env.EXISTS == 'false'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v${PACKAGE_VERSION}" -m "Release v${PACKAGE_VERSION}"
          git push origin "v${PACKAGE_VERSION}"

      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: CHANGELOG.md
          skip-commit: false
          tag-prefix: ""

      - name: Create GitHub Release
        if: env.EXISTS == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.PACKAGE_VERSION }}"
          name: "v${{ env.PACKAGE_VERSION }}"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build package
        if: env.EXISTS == 'false'
        run: npm run build --if-present

      - name: Publish to npm
        if: env.EXISTS == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}